Repository hmcts/sds-toffee-recipes-service, pull requests merged in 2022-06, with the labels that each got.

#39 DTSPO-8276 - Fix failing security checks
  build.gradle
  charts/toffee-recipe-backend/Chart.yaml
  dependency-check-suppressions.xml
Labels: ns:toffee, prd:toffee, rel:toffee-recipe-backend-pr-39

#40 DTSPO-8276 - Create CODEOWNERS file
  CODEOWNERS
Labels: ns:toffee, prd:toffee, rel:toffee-recipe-backend-pr-40

#44 Update spring boot
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:toffee, prd:toffee, rel:toffee-recipe-backend-pr-44
