Repository hmcts/sds-toffee-recipes-service, pull requests merged in 2025-03, with the labels that each got.

#628 Adding conditional logic to create_mode for psql flex
  infrastructure/main.tf
Labels: ns:toffee, prd:apple, prd:toffee, stg/no-changes, prod/no-changes, rel:toffee-recipe-backend-pr-628, sbox/destroy, rel:apple-recipe-backend-pr-628

#631 Fix expiresAfter tag
  Jenkinsfile_CNP
Labels: ns:toffee, prd:toffee, rel:toffee-recipe-backend-pr-631

#633 DTSPO-24722 - Test flex server restore via terraform
  infrastructure/main.tf
  infrastructure/sbox.tfvars
Labels: ns:toffee, prd:toffee, stg/add-or-update, prod/no-changes, rel:toffee-recipe-backend-pr-633

#636 DTSPO-24722 - Test flex server restore via terraform - 2
  infrastructure/main.tf
Labels: ns:toffee, prd:toffee, stg/add-or-update, prod/no-changes, rel:toffee-recipe-backend-pr-636
